[workspace]
members = ["tools/gardener"]
resolver = "2"

[workspace.lints.clippy]
unwrap_used = "deny"
unnecessary_sort_by = "deny"
expect_used = "deny"
same_functions_in_if_condition = "deny"
needless_late_init = "deny"
identity_op = "deny"
needless_update = "warn"
unnecessary_lazy_evaluations = "deny"
redundant_static_lifetimes = "deny"
unnecessary_to_owned = "warn"
manual_memcpy = "deny"
manual_clamp = "deny"
manual_find = "deny"
manual_range_contains = "deny"
manual_filter = "deny"
manual_flatten = "deny"
manual_map = "deny"
manual_non_exhaustive = "deny"
manual_ok_or = "deny"
manual_retain = "deny"
manual_strip = "deny"
manual_try_fold = "deny"
manual_unwrap_or = "warn"
needless_borrowed_reference = "warn"
needless_option_as_deref = "deny"
needless_question_mark = "warn"
