[workspace]
members = ["tools/gardener"]
resolver = "2"

[workspace.lints.clippy]
unwrap_used = "deny"
unnecessary_sort_by = "warn"
expect_used = "warn"
needless_late_init = "warn"
identity_op = "deny"
needless_update = "warn"
unnecessary_lazy_evaluations = "warn"
redundant_static_lifetimes = "deny"
manual_memcpy = "warn"
manual_clamp = "warn"
manual_find = "warn"
manual_range_contains = "warn"
manual_filter = "warn"
manual_flatten = "warn"
manual_map = "warn"
manual_non_exhaustive = "warn"
manual_ok_or = "warn"
manual_retain = "warn"
manual_strip = "warn"
manual_try_fold = "warn"
manual_unwrap_or = "warn"
needless_borrowed_reference = "warn"
